from django.urls import path,include
from . import views

urlpatterns = [
    path("",views.visitpage,name="visitpage"),
    path("patienthomepage",views.patienthomepage,name="patienthomepage"),
    path('loginpage',views.loginpage,name="login"),
    path('regpage',views.regpage,name='register'),
    path('doctordashboard',views.doctordashboard,name='doctordashboard'),
    path('patientdashboard',views.patientdashboard,name="patientdashboard"),
    path('favourites',views.favourites,name='favourites'),
    path('doctorprofile/<int:pk>',views.doctorprofile,name='doctorprofile'),
    path('chat',views.chat,name='chat'),
    path('profilesetting',views.profilesetting,name='profilesetting'),
    path('changepassword',views.changepassword,name='changepassword'),
    path('doctorregister',views.doctorregister,name='doctorregister'),
    path('Pharmaregistration',views.Pharmaregistration,name='Pharmareg'),
    path('registeruser',views.registeruser,name='registeruser'),
    path('loginuser',views.loginuser,name='loginuser'),
    path('showdata',views.showdata,name='showdata'),
    # path('admindashboard',views.admindashboard,name='admindashboard'),
    path('bookingpage/<int:pk>',views.bookingpage,name='bookingpage'),
    # path('booking_appointment/<int:pk>',views.booking_appointment,name='booking_appointment'),
    path('appointment_stutusA/<int:pk>',views.appointment_stutusA,name='appointment_stutusA'),
    path('appointment_stutusR/<int:pk>',views.appointment_stutusR,name='appointment_stutusR'),
    path('appointments',views.appointments,name='appointments'),
    path('schedule',views.schedule,name='schedule'),
    path('schedule_timing',views.schedule_timing,name='schedule_timing'),
    # path('newbooking',views.newbooking,name='newbooking'),
    path('calendar',views.calendar,name='calendar'),
    path('bookappoint/<int:pk>',views.bookappoint,name='bookappoint'),
    path('mypatient',views.mypatient,name='mypatient'),
    # path('booksuccess/<int:pk>',views.booksuccess,name='booksuccess'),
    path('patientbookhistory',views.patientbookhistory,name='patientbookhistory'),
    path('doctor_profile1/<int:pk>',views.doctor_profile1,name='doctor_profile1'),
    path('speciality',views.speciality,name='speciality'),
    path('Surgeon',views.Surgeon,name='Surgeon'),
    path('Radiologist',views.Radiologist,name='Radiologist'),
    path('Cardiologist1',views.Cardiologist1,name='Cardiologist1'),
    path('Surgeon1',views.Surgeon1,name='Surgeon1'),
    path('Radiologist1',views.Radiologist1,name='Radiologist1'),
    path('patientprofilesettings',views.patientprofilesettings,name='patientprofilesettings'),
    path('edit_user',views.edit_user,name='edit_user'),
    path('doctorprofilesettings',views.doctorprofilesettings,name='doctorprofilesettings'),
    path('edit_doctorprofile',views.edit_doctorprofile,name='edit_doctorprofile'),
    path('ds_appointments',views.ds_appointments,name='ds_appointments'),
    path('ds_mypatients',views.ds_mypatients,name='ds_mypatients'),
    path('doctors',views.doctors,name='doctors'),
    path('doctors1',views.doctors1,name='doctors1'),
    path('specia',views.specia,name='specia'),  
    path('specia1',views.specia1,name='specia1'),
    
    
    
    path('reviews',views.reviews,name='reviews'),
    path('doctorchangepassword',views.doctorchangepassword,name='doctorchangepassword'),

    path('admin_appointment',views.admin_appointment,name='admin_appointment'),
    path('admin_specialities',views.admin_specialities,name='admin_specialities'),
    path('admin_doctor',views.admin_doctor,name='admin_doctor'),
    path('admin_patient',views.admin_patient,name='admin_patient'),
    path('admin_reviews',views.admin_reviews,name='admin_reviews'),
    path('admin_transactions',views.admin_transactions,name='admin_transactions'),
    path('admin_settings',views.admin_settings,name='admin_settings'),
    path('admin_invoice',views.admin_invoice,name='admin_invoice'),
    path('admin_login',views.admin_login,name='admin_login'),
    path('admin_register',views.admin_register,name='admin_register'),
    path('admin_forgotpassword',views.admin_forgotpassword,name='admin_forgotpassword'),
    path('admin_lockscreen',views.admin_lockscreen,name='admin_lockscreen'),
    path('error404',views.error404,name='error404'),
    path('admin_error500',views.admin_error500,name='admin_error500'),
    path('blankpage',views.blankpage,name='blankpage'),
    path('components',views.components,name='components'),
    path('form_basicinput',views.form_basicinput,name='form_basicinput'),
    path('form_inputgroup',views.form_inputgroup,name='form_inputgroup'),
    path('adminlogin',views.adminlogin,name='adminlogin'),
    path('form_horizontal',views.form_horizontal,name='form_horizontal'),
    path('form_vertical',views.form_vertical,name='form_vertical'),
    path('admin_dashboard',views.admin_dashboard,name='admin_dashboard'),
    path('review/<int:pk>',views.review,name='review'),
    path('logout',views.logout,name='logout'),
    path('patientchngpwdpage',views.patientchngpwdpage,name='patientchngpwdpage'),
    path('patientchangepas',views.patientchangepas,name='patientchangepas'),
    
    path('Email/<int:pk>/',views.Email,name='Email'),
    path('emailpatient/<int:pk>/',views.emailpatient,name='emailpatient'),
    path('varification/<int:pk>/',views.varification,name='varification'),
    path('varificationpage/<int:pk>/',views.varificationpage,name='varificationpage'),
    path('forgotPassword',views.forgotPassword,name='forgotPassword'),
    path('forgotpass',views.forgotpass,name='forgotpass'),
    path('forgetpwdvarification/<int:pk>/',views.forgetpwdvarification,name='forgetpwdvarification'),
    path('forgetvarification/<int:pk>/',views.forgetvarification,name='forgetvarification'),
    path('forgotchangepwdpage/<int:pk>/',views.forgotchangepwdpage,name='forgotchangepwdpage'),
    path('forgotchangepwd/<int:pk>/',views.forgotchangepwd,name='forgotchangepwd'),
    path('searchresult',views.searchresult,name='searchresult'),
    path('appointmentlist',views.appointmentlist,name='appointmentlist'),
    path('adminpro',views.adminpro,name='adminpro'),
    path('delete_details/<int:pk>/',views.delete_details,name='delete_details'),
    path('delete_user/<int:pk>/',views.delete_user,name='delete_user'),
    path('delete_patient/<int:pk>/',views.delete_patient,name='delete_patient'),
    path('reportpage',views.reportpage,name='reportpage'),
    path('reportgen',views.reportgen,name='reportgen'),
    path('delete_report/<int:pk>/',views.delete_report,name='delete_report'),
    path('bloggrid',views.bloggrid,name='bloggrid'),
    path('reply/<int:pk>/',views.reply,name='reply'),
    path('docreply/<int:pk>/',views.docreply,name='docreply')
    


 
  
]